version: "3.8"
services:
  myapp-mysql:
    image: mysql:5.7
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=BackCNSTN
    ports:
      - 3306:3306
  myapp-main:
    image: aymenn25/monback
    depends_on:
      - myapp-mysql
    ports:
      - 8082:8082
    environment:
      - SPRING_DATASOURCE_PASSWORD=root
      - SERVER_PORT=8082
      - SPRING_DATASOURCE_URL=jdbc:mysql://myapp-mysql:3306/BackCNSTN?createDatabaseIfNotExist=true&serverTimezone=UTC
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT=org.hibernate.dialect.MySQL8Dialect
    volumes:
      - ./data:/var/myapp/data
  front:
    image: aymenn25/front
    depends_on:
      - myapp-main	
    ports:
      - 4200:80

  